# Generated by Django 4.2.25 on 2025-11-09 16:49
#talleres/migrations/0001_initial.py
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
    ]
