# Generated by Django 4.2.25 on 2025-11-09 16:59
#talleres/migrations/0002_state_sync.py
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('talleres', '0001_initial'),
    ]

    operations = [
    ]
