# Generated by Django 4.2.25 on 2025-11-19 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('talleres', '0002_state_sync'),
    ]

    operations = [
        migrations.CreateModel(
            name='Taller',
            fields=[
                ('taller_id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('ubicacion', models.CharField(max_length=100)),
                ('encargado_taller', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'talleres',
                'managed': False,
            },
        ),
    ]
