# Generated by Django 4.2.25 on 2025-10-29 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('rut', models.CharField(max_length=12, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('cargo', models.CharField(max_length=50)),
                ('region', models.CharField(blank=True, max_length=50, null=True)),
                ('horario', models.CharField(blank=True, max_length=100, null=True)),
                ('disponibilidad', models.PositiveSmallIntegerField(default=1)),
                ('usuario', models.CharField(max_length=45, unique=True)),
                ('taller_id', models.IntegerField(default=1)),
                ('password', models.CharField(max_length=128)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('is_superuser', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'empleados',
                'managed': False,
            },
        ),
    ]
