# Generated by Django 4.2.25 on 2025-11-19 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('autenticacion', '0002_state_sync'),
    ]

    operations = [
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('rut', models.CharField(max_length=12, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('cargo', models.CharField(choices=[('CHOFER', 'Chofer'), ('SUPERVISOR', 'Supervisor'), ('MECANICO', 'Mecánico'), ('ADMINISTRATIVO', 'Administrativo')], max_length=20)),
                ('region', models.CharField(blank=True, choices=[('XV', 'Arica y Parinacota'), ('I', 'Tarapacá'), ('II', 'Antofagasta'), ('III', 'Atacama'), ('IV', 'Coquimbo'), ('V', 'Valparaíso'), ('RM', 'Región Metropolitana'), ('VI', 'O’Higgins'), ('VII', 'Maule'), ('XVI', 'Ñuble'), ('VIII', 'Biobío'), ('IX', 'La Araucanía'), ('XIV', 'Los Ríos'), ('X', 'Los Lagos'), ('XI', 'Aysén'), ('XII', 'Magallanes')], max_length=10, null=True)),
                ('horario', models.CharField(choices=[('07:00-16:00', '07:00 a 16:00'), ('08:00-17:00', '08:00 a 17:00'), ('09:00-18:00', '09:00 a 18:00'), ('10:00-19:00', '10:00 a 19:00')], default='08:00-17:00', max_length=20)),
                ('disponibilidad', models.BooleanField(default=True)),
                ('password', models.CharField(max_length=128)),
                ('usuario', models.CharField(max_length=45, unique=True)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('is_superuser', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'empleados',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Taller',
            fields=[
                ('taller_id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('ubicacion', models.CharField(max_length=100)),
                ('encargado_taller', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'talleres',
                'managed': False,
            },
        ),
    ]
