# Generated by Django 4.2.25 on 2025-11-09 16:53
# documentos/migrations/0001_initial.py
from django.db import migrations, models
import django.db.models.deletion
import documentos.models


class Migration(migrations.Migration):

    initial = True

    # 🔧 IMPORTANTE:
    # Antes dependía de:
    #   ('ordenestrabajo', '0002_create_pausa'),
    #   ('vehiculos', '0002_initial'),
    # Pero esas migraciones ya no existen (apps legacy con managed=False).
    # Dejamos la lista vacía para que esta migración no espere esas dependencias.
    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Documento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(
                    choices=[
                        ('FOTO', 'Fotografía'),
                        ('INFORME', 'Informe'),
                        ('OTRO', 'Otro'),
                    ],
                    default='OTRO',
                    max_length=12,
                )),
                ('titulo', models.CharField(max_length=200)),
                ('archivo', models.FileField(upload_to=documentos.models.upload_to_ot)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('ot', models.ForeignKey(
                    blank=True,
                    null=True,
                    on_delete=django.db.models.deletion.CASCADE,
                    related_name='documentos',
                    to='ordenestrabajo.ordentrabajo',
                )),
                ('patente', models.ForeignKey(
                    blank=True,
                    db_column='patente',
                    db_constraint=False,
                    null=True,
                    on_delete=django.db.models.deletion.RESTRICT,
                    related_name='documentos',
                    to='vehiculos.vehiculo',
                )),
            ],
            options={
                'db_table': 'documentos',
                'ordering': ['-creado_en'],
            },
        ),
    ]
