# Generated by Django 4.2.25 on 2025-11-19 23:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documentos', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='documento',
            options={'managed': False, 'ordering': ['-creado_en']},
        ),
    ]
