# Generated by Django 4.2.25 on 2025-11-09 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vehiculos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehiculo',
            fields=[
                ('patente', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('marca', models.CharField(max_length=50)),
                ('modelo', models.CharField(max_length=50)),
                ('anio', models.IntegerField(blank=True, null=True)),
                ('tipo', models.CharField(blank=True, max_length=50, null=True)),
                ('estado', models.CharField(default='Disponible', max_length=50)),
                ('ubicacion', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'vehiculos',
                'managed': False,
            },
        ),
    ]
