#ordenestrabajo/migrations/0001_initial.py
# Generated by Django 4.2.25 on 2025-10-29 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OrdenTrabajo',
            fields=[
                ('ot_id', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_ingreso', models.DateField()),
                ('fecha_salida', models.DateField(blank=True, null=True)),
                ('descripcion', models.CharField(blank=True, max_length=255, null=True)),
                ('estado', models.CharField(default='Pendiente', max_length=50)),
                ('patente', models.CharField(max_length=20)),
                ('taller_id', models.IntegerField()),
                ('rut', models.CharField(max_length=12)),
            ],
            options={
                'db_table': 'ordenestrabajo',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Repuesto',
            fields=[
                ('repuesto_id', models.AutoField(primary_key=True, serialize=False)),
                ('ot_id', models.IntegerField()),
                ('nombre', models.CharField(max_length=100)),
                ('cantidad', models.IntegerField()),
                ('descripcion', models.TextField()),
            ],
            options={
                'db_table': 'repuestos',
                'managed': False,
            },
        ),
    ]
