# Generated by Django 4.2.25 on 2025-11-09 16:49
#ordenestrabajo/migrations/0002_create_pausa.py
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ordenestrabajo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Incidente',
            fields=[
                ('incidente_id', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateTimeField(blank=True, null=True)),
                ('descripcion', models.CharField(max_length=1000)),
            ],
            options={
                'db_table': 'incidentes',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Llave',
            fields=[
                ('llave_id', models.AutoField(primary_key=True, serialize=False)),
                ('estado', models.CharField(default='Disponible', max_length=50)),
            ],
            options={
                'db_table': 'llaves',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='OrdenTrabajo',
            fields=[
                ('ot_id', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_ingreso', models.DateField()),
                ('hora_ingreso', models.TimeField(blank=True, null=True)),
                ('fecha_salida', models.DateField(blank=True, null=True)),
                ('descripcion', models.CharField(blank=True, max_length=255, null=True)),
                ('estado', models.CharField(default='Pendiente', max_length=50)),
            ],
            options={
                'db_table': 'ordenestrabajo',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PrestamoVehiculo',
            fields=[
                ('prestamo_id', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField(blank=True, null=True)),
                ('estado', models.CharField(default='En uso', max_length=50)),
            ],
            options={
                'db_table': 'prestamosvehiculos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Repuesto',
            fields=[
                ('repuesto_id', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad', models.IntegerField(default=1)),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.CharField(blank=True, max_length=500, null=True)),
            ],
            options={
                'db_table': 'repuestos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Pausa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motivo', models.CharField(max_length=120)),
                ('observacion', models.TextField(blank=True, default='')),
                ('inicio', models.DateTimeField(auto_now_add=True)),
                ('fin', models.DateTimeField(blank=True, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('ot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pausas', to='ordenestrabajo.ordentrabajo')),
            ],
            options={
                'db_table': 'pausas',
                'ordering': ['-inicio'],
            },
        ),
    ]
