# Generated by Django 4.2.25 on 2025-11-19 23:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ordenestrabajo', '0002_create_pausa'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Incidente',
        ),
        migrations.DeleteModel(
            name='Llave',
        ),
        migrations.DeleteModel(
            name='PrestamoVehiculo',
        ),
        migrations.DeleteModel(
            name='Repuesto',
        ),
    ]
