# Generated by Django 4.2.25 on 2025-11-23 02:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('autenticacion', '0003_initial'),
        ('talleres', '0003_initial'),
        ('vehiculos', '0002_initial'),
        ('ordenestrabajo', '0003_delete_incidente_delete_llave_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SolicitudIngresoVehiculo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_solicitada', models.DateField()),
                ('descripcion', models.CharField(blank=True, max_length=255)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('APROBADA', 'Aprobada'), ('RECHAZADA', 'Rechazada'), ('CERRADA', 'Cerrada')], default='PENDIENTE', max_length=10)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('chofer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='solicitudes_ingreso', to='autenticacion.empleado')),
                ('taller', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='solicitudes_ingreso', to='talleres.taller')),
                ('vehiculo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='solicitudes_ingreso', to='vehiculos.vehiculo')),
            ],
            options={
                'verbose_name': 'Solicitud de Ingreso de Vehículo',
                'verbose_name_plural': 'Solicitudes de Ingreso de Vehículos',
                'db_table': 'solicitudes_ingreso_vehiculo',
                'ordering': ['-creado_en'],
            },
        ),
    ]
